# Build stage
FROM node:23 as build
WORKDIR /app
COPY package*.json ./ 
RUN npm install
COPY . . 
RUN npm run build

# Production stage
FROM nginx:alpine

# Copy the build output to the Nginx html folder
COPY --from=build /app/dist /usr/share/nginx/html

# Copy the custom nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
