services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./backend/.env
    working_dir: /usr/src/app
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile.dev
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./frontend/.env
    working_dir: /usr/src/app
    command: npm run dev
