version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - ./.env
    working_dir: /usr/src/app
    command: npm run dev

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/usr/src/app
    working_dir: /usr/src/app
    command: npm run dev
