services:
  - type: web
    name: dms-backend
    env: docker
    repo: https://github.com/peerawet/TPS
    branch: main
    rootDir: backend
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false

  - type: web
    name: dms-frontend
    env: docker
    repo: https://github.com/peerawet/TPS
    branch: main
    rootDir: frontend
    plan: free
