services:
  - type: web
    name: dms-backend
    env: docker
    repo: https://github.com/peerawet/TPS
    branch: main
    rootDir: backend
    plan: free
    envVars:
      - group: TPS-Backend-Env

  - type: web
    name: dms-frontend
    env: docker
    repo: https://github.com/peerawet/TPS
    branch: main
    rootDir: frontend
    plan: free
    envVars:
      - group: TPS-Frontend-Env
