FROM node:23
# ใช้ official Node.js image เวอร์ชัน 23 เป็น base image

WORKDIR /usr/src/app
# ตั้ง working directory ภายใน container เป็น /usr/src/app

COPY package*.json ./
# คัดลอกไฟล์ package.json และ package-lock.json (ถ้ามี) เข้ามาใน working directory ของ container

RUN npm install
# รันคำสั่ง npm install เพื่อติดตั้ง dependencies ที่ระบุใน package.json

COPY . .
# คัดลอกไฟล์และโฟลเดอร์ทั้งหมดจาก host ไปยัง working directory ภายใน container

EXPOSE 5000
# แจ้งให้ Docker ทราบว่า container จะฟัง (listen) บนพอร์ต 5000

CMD ["npm", "run", "dev"]
# กำหนดคำสั่งเริ่มต้น เมื่อ container รัน คือ npm run dev (เรียกสคริปต์ dev ใน package.json)